project:
  type: book

book:
  title: "Statistical analysis and presentation using R"
  subtitle: "An overview of R functions used in Statistics I"
  author: "Tom Louwerse & Tim Mickler"
  date: "2024-02-01"
  chapters:
    - index.qmd
    - part: part_working_data.qmd
      chapters:
      - data_01_basics.qmd
      - data_02_filtering_selecting.qmd
      - data_03_variables.qmd
      - data_04_missing_data.qmd
      - data_05_advanced_recoding.qmd
      - data_06_merging_data.qmd
    - part: part_statistical_analysis.qmd
      chapters:
      - analysis_01_descriptives.qmd
      - analysis_02_graphs.qmd
      - analysis_03_tables.qmd
      - analysis_04_probability.qmd
      - analysis_05_normal_distribution.qmd
      - analysis_06_proportions.qmd
      - analysis_07_chi_squared.qmd
      - analysis_08_t-test.qmd
      - analysis_09_power_analysis.qmd
      - analysis_10_anova.qmd
  appendices:
    - common_errors.qmd

format:
  html:
    theme: cosmo

editor: 
  mode: source

