<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>14&nbsp; T-tests for means – Statistical analysis and presentation using R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./analysis_09_power_analysis.html" rel="next">
<link href="./analysis_07_chi_squared.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./part_statistical_analysis.html">Statistical analysis in R</a></li><li class="breadcrumb-item"><a href="./analysis_08_t-test.html"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">T-tests for means</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Statistical analysis and presentation using R</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./part_working_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Working with data in R</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data_01_basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Working with R and RStudio: the basics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data_02_filtering_selecting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Filtering, selecting &amp; renaming</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data_03_variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Creating, summarising &amp; recoding variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data_04_missing_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Missing data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data_05_advanced_recoding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Advanced recoding of variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data_06_merging_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Combining &amp; joining data sets</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./part_statistical_analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Statistical analysis in R</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./analysis_01_descriptives.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Measures of central tendency and dispersion</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./analysis_02_graphs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Graphing using ggplot2</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./analysis_03_tables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Tables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./analysis_04_probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Probability in R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./analysis_05_normal_distribution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Normal distribution</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./analysis_06_proportions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Inference for proportions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./analysis_07_chi_squared.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Chi-squared and measures of association</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./analysis_08_t-test.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">T-tests for means</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./analysis_09_power_analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Power analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./analysis_10_anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">ANOVA</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./common_errors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Common errors in R</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#standard-error-of-the-mean" id="toc-standard-error-of-the-mean" class="nav-link active" data-scroll-target="#standard-error-of-the-mean"><span class="header-section-number">14.1</span> Standard error of the mean</a></li>
  <li><a href="#t-tests" id="toc-t-tests" class="nav-link" data-scroll-target="#t-tests"><span class="header-section-number">14.2</span> T-tests</a>
  <ul class="collapse">
  <li><a href="#one-sample-t-test" id="toc-one-sample-t-test" class="nav-link" data-scroll-target="#one-sample-t-test"><span class="header-section-number">14.2.1</span> One sample t-test</a></li>
  <li><a href="#reporting-a-one-sample-t-test" id="toc-reporting-a-one-sample-t-test" class="nav-link" data-scroll-target="#reporting-a-one-sample-t-test"><span class="header-section-number">14.2.2</span> Reporting a one-sample t-test</a></li>
  <li><a href="#paired-samples-t-test" id="toc-paired-samples-t-test" class="nav-link" data-scroll-target="#paired-samples-t-test"><span class="header-section-number">14.2.3</span> Paired samples t-test</a></li>
  <li><a href="#reporting-a-paired-samples-t-test" id="toc-reporting-a-paired-samples-t-test" class="nav-link" data-scroll-target="#reporting-a-paired-samples-t-test"><span class="header-section-number">14.2.4</span> Reporting a paired samples t-test</a></li>
  <li><a href="#independent-samples-t-test" id="toc-independent-samples-t-test" class="nav-link" data-scroll-target="#independent-samples-t-test"><span class="header-section-number">14.2.5</span> Independent-samples t-test</a></li>
  <li><a href="#reporting-an-independent-samples-t-test" id="toc-reporting-an-independent-samples-t-test" class="nav-link" data-scroll-target="#reporting-an-independent-samples-t-test"><span class="header-section-number">14.2.6</span> Reporting an independent samples t-test</a></li>
  </ul></li>
  <li><a href="#effect-sizes-for-t-tests" id="toc-effect-sizes-for-t-tests" class="nav-link" data-scroll-target="#effect-sizes-for-t-tests"><span class="header-section-number">14.3</span> Effect sizes for t-tests</a>
  <ul class="collapse">
  <li><a href="#cohens-d-for-one-sample" id="toc-cohens-d-for-one-sample" class="nav-link" data-scroll-target="#cohens-d-for-one-sample"><span class="header-section-number">14.3.1</span> Cohen’s <span class="math inline">\(d\)</span> for one sample</a></li>
  <li><a href="#cohens-d-for-paired-samples" id="toc-cohens-d-for-paired-samples" class="nav-link" data-scroll-target="#cohens-d-for-paired-samples"><span class="header-section-number">14.3.2</span> Cohen’s d for paired samples</a></li>
  <li><a href="#hedges-g_s-for-independent-samples" id="toc-hedges-g_s-for-independent-samples" class="nav-link" data-scroll-target="#hedges-g_s-for-independent-samples"><span class="header-section-number">14.3.3</span> Hedges’ <span class="math inline">\(g^*_s\)</span> for independent samples</a></li>
  <li><a href="#reporting-measures-of-association-for-t-tests" id="toc-reporting-measures-of-association-for-t-tests" class="nav-link" data-scroll-target="#reporting-measures-of-association-for-t-tests"><span class="header-section-number">14.3.4</span> Reporting measures of association for t-tests</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./part_statistical_analysis.html">Statistical analysis in R</a></li><li class="breadcrumb-item"><a href="./analysis_08_t-test.html"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">T-tests for means</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-analysis-t-test" class="quarto-section-identifier"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">T-tests for means</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>We use data from the 2019 Canadian Election Study as an example in this chapter:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>canada <span class="ot">&lt;-</span> <span class="fu">import</span>(<span class="st">"2019 Canadian Election Study.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="standard-error-of-the-mean" class="level2" data-number="14.1">
<h2 data-number="14.1" class="anchored" data-anchor-id="standard-error-of-the-mean"><span class="header-section-number">14.1</span> Standard error of the mean</h2>
<p>The standard error of the mean can be estimated as <span class="math inline">\(\frac{s}{\sqrt{n}}\)</span>. In R we can use the function <code>MeanSE</code> from package <code>DescTools</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(DescTools)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>example_vector <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">20</span>)  <span class="co"># Example data of 20 normally distributed random numbers.</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">MeanSE</span>(<span class="at">x =</span> example_vector, </span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1487493</code></pre>
</div>
</div>
<dl>
<dt><code>MeanSE(…)</code></dt>
<dd>
<p>This function calculates the standard error of the mean for a vector of numbers.</p>
</dd>
<dt><code>x = example_vector</code></dt>
<dd>
<p>We want to calculate the SE of the Mean for the values in <code>example_vector</code>. For your own data, you would change this to the appropriate vector name.</p>
</dd>
<dt><code>na.rm = TRUE</code></dt>
<dd>
<p>This option ensures that any missing values are ignored.</p>
</dd>
</dl>
<p>You can also use <code>MeanSE</code> for a variable in a data frame:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Using $ to select a variable from a data frame</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">MeanSE</span>(canada<span class="sc">$</span>cps19_age, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.08541655</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Using function summarise</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>canada <span class="sc">|&gt;</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">SE_age =</span> <span class="fu">MeanSE</span>(cps19_age, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      SE_age
1 0.08541655</code></pre>
</div>
</div>
<p>The <code>describe</code> function in package <code>psych</code> provides the Standard Error for the Mean for all variables in a data frame. It is particularly useful when we would like to quickly calculate the standard error for multiple variables. In this example we select three interval-ratio variables from the 2019 Canadian Election Study (which we imported above):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(psych)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Select three variables from 'canada' and assign to dataset 'canada_selection'</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>canada_selection <span class="ot">&lt;-</span> canada <span class="sc">|&gt;</span> </span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(cps19_age, cps19_lr_parties_1, cps19_lr_parties_2)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Use describe to calculate summary statistics for 'canada_selection'</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a><span class="fu">describe</span>(canada_selection)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   vars     n  mean    sd median trimmed   mad min max range
cps19_age             1 37822 48.69 16.61     49   48.66 20.76  18  99    81
cps19_lr_parties_1    2 27743  4.27  2.79      4    4.19  2.97   0  10    10
cps19_lr_parties_2    3 28210  6.90  2.79      8    7.28  2.97   0  10    10
                    skew kurtosis   se
cps19_age           0.04    -0.91 0.09
cps19_lr_parties_1  0.19    -0.77 0.02
cps19_lr_parties_2 -0.97     0.14 0.02</code></pre>
</div>
</div>
<p>The column <code>se</code> displays the standard error of the mean (by default rounded to two decimals).</p>
</section>
<section id="t-tests" class="level2" data-number="14.2">
<h2 data-number="14.2" class="anchored" data-anchor-id="t-tests"><span class="header-section-number">14.2</span> T-tests</h2>
<section id="one-sample-t-test" class="level3" data-number="14.2.1">
<h3 data-number="14.2.1" class="anchored" data-anchor-id="one-sample-t-test"><span class="header-section-number">14.2.1</span> One sample t-test</h3>
<p>To calculate a one sample t-test we use the function <code>t.test</code>:</p>
<p>In the below example we measure whether the age of respondents is different from a hypothesized mean of 48.5:<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(<span class="at">formula =</span> cps19_age <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">data =</span> canada,</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">alternative =</span> <span class="st">"two.sided"</span>,</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">mu =</span> <span class="fl">48.5</span>,</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">conf.level =</span> <span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  cps19_age
t = 2.2395, df = 37821, p-value = 0.02513
alternative hypothesis: true mean is not equal to 48.5
95 percent confidence interval:
 48.52387 48.85871
sample estimates:
mean of x 
 48.69129 </code></pre>
</div>
</div>
<dl>
<dt><code>formula = cps19_age ~ 1</code></dt>
<dd>
<p>As we have only one variable in a one sample t-test, we specify the formula in the form <code>&lt;variable name&gt; ~ 1</code>.</p>
</dd>
<dt><code>data = canada</code></dt>
<dd>
<p>We specify the data frame that we want to use.</p>
</dd>
<dt><code>alternative = "two.sided"</code></dt>
<dd>
<p>Determines whether we want to use a two sided-test, or a one-sided test. Options are “two.sided” (default), “less” (when <span class="math inline">\(H_1: \mu &lt; p\)</span>) or “greater” (when <span class="math inline">\(H_1: \mu &gt; p\)</span>).</p>
</dd>
<dt><code>mu = 48.5</code></dt>
<dd>
<p>The <code>mu</code> parameter should be set to the value of the mean <em>under the null hypothesis</em>.</p>
</dd>
<dt><code>conf.level = 0.95</code></dt>
<dd>
<p>This specifies the confidence level of the confidence interval reported. The default is 0.95 (a 95% confidence interval).</p>
</dd>
</dl>
</section>
<section id="reporting-a-one-sample-t-test" class="level3" data-number="14.2.2">
<h3 data-number="14.2.2" class="anchored" data-anchor-id="reporting-a-one-sample-t-test"><span class="header-section-number">14.2.2</span> Reporting a one-sample t-test</h3>
<p>We illustrate the one-sample t-test using data on the fruit consumption of students. We test whether the fruit consumption is significantly different from a population value of 100.</p>
<p><em>Example output R (do not include the output directly in an academic paper):</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">MeanSE</span>(fruit<span class="sc">$</span>fruitconsumption)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.714986</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(<span class="at">x =</span> fruit<span class="sc">$</span>fruitconsumption,</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>           <span class="at">alternative =</span> <span class="st">"two.sided"</span>,</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">mu =</span> <span class="dv">100</span>,</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">conf.level =</span> <span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  fruit$fruitconsumption
t = -5.831, df = 33, p-value = 1.587e-06
alternative hypothesis: true mean is not equal to 100
95 percent confidence interval:
 86.51084 93.48916
sample estimates:
mean of x 
       90 </code></pre>
</div>
</div>
<!-- *Example output SPSS (do not include the output directly in an academic paper):* -->
<!-- ![](docs/spss_one_sample_ttest.png) -->
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Output explanation
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>In R, the output shows:
<ul>
<li>the mean of the observations in the sample (see ‘mean of x’).</li>
<li>the calculated t-value (see ‘t =’).</li>
<li>the degrees of freedom (see ‘df =’).</li>
<li>the p-value (i.e.&nbsp;the probability of finding the obtained t-value, given the null hypothesis).</li>
<li>the expected value under the null hypothesis (here 100, see “true mean is not equal to 100”).</li>
<li>the standard error of the observations in the sample is obtained separately via <code>MeanSE()</code>.</li>
</ul></li>
</ul>
<!-- In SPSS, the information is presented in two tables.  -->
<!-- * In the table 'One-Sample Statistics', we find -->
<!--   +the mean of the observations in the sample (see cell 'Mean'). -->
<!--   +the standard error (see cell 'Std. Error Mean'). -->
<!-- * In the SPSS table 'One-Sample Test', we find -->
<!--   +the calculated t-value (see cell 't'). -->
<!--   +the degrees of freedom (see cell 'df'). -->
<!--   +the p-value (i.e. the probability of finding the obtained t-value, given the null hypothesis. -->
<!--   +the expected value under the null hypothesis (here 100, see "Test Value = 100"). -->
</div>
</div>
<section id="reporting" class="level4" data-number="14.2.2.1">
<h4 data-number="14.2.2.1" class="anchored" data-anchor-id="reporting"><span class="header-section-number">14.2.2.1</span> Reporting</h4>
<p>The correct report includes:</p>
<ul>
<li>A conclusion about the null hypothesis; followed by</li>
<li>the mean (in the text or as M = …) and the standard error (SE = …) of the sample.</li>
<li>t(degrees of freedom)</li>
<li>p = p-value. When working with statistical software, you should report the exact p-value that is displayed.
<ul>
<li>in R, small values may be displayed using the scientific notation (e.g.&nbsp;2.2e-16 is the scientific notation of 0.00000000000000022.) This means that the value is very close to zero. R uses this notation automatically for very small numbers. In these cases, write p &lt; 0.001 in your report. <!-- + in  SPSS, very small p-values may be displayed as p=0.000. However, never write p=0.000 in your report. This is simply the way SPSS displays very small p-values < 0.0005. In these cases, write p < 0.001 in your report. --></li>
</ul></li>
<li>If you calculate the t-value by hand you would write p &lt; / = / &gt; your chosen <span class="math inline">\(\alpha\)</span>-level.</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Report
</div>
</div>
<div class="callout-body-container callout-body">
<p>✓ The mean fruit consumption of students was 90 (SE = 1.71). This is significantly different from the mean fruit consumption of the whole population (t(33) = -5.83, p &lt; 0.001).</p>
</div>
</div>
<p>Below you find an example of a non-significant result. In this case we test whether the fruit consumption is significantly different from a population value of 92.</p>
<p><em>Example output R (do not include the output directly in an academic paper):</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">MeanSE</span>(fruit<span class="sc">$</span>fruitconsumption, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.714986</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(<span class="at">x =</span> fruit<span class="sc">$</span>fruitconsumption,</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>           <span class="at">alternative =</span> <span class="st">"two.sided"</span>,</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">mu =</span> <span class="dv">92</span>,</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">conf.level =</span> <span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  fruit$fruitconsumption
t = -1.1662, df = 33, p-value = 0.2519
alternative hypothesis: true mean is not equal to 92
95 percent confidence interval:
 86.51084 93.48916
sample estimates:
mean of x 
       90 </code></pre>
</div>
</div>
<!-- *Example output SPSS (do not include the output directly in an academic paper):* -->
<!-- ![](docs/spss_one_sample_ttest_2.png) -->
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Report
</div>
</div>
<div class="callout-body-container callout-body">
<p>✓ The mean fruit consumption of students was 90 (SE = 1.71). This is not significantly different from the mean fruit consumption of the whole population (t(33) = -1.167, p = 0.252).</p>
</div>
</div>
</section>
</section>
<section id="paired-samples-t-test" class="level3" data-number="14.2.3">
<h3 data-number="14.2.3" class="anchored" data-anchor-id="paired-samples-t-test"><span class="header-section-number">14.2.3</span> Paired samples t-test</h3>
<p>In a paired samples t-test we compare the mean value of two interval-ratio variables.</p>
<p>In the below example we test the null hypothesis that the mean difference of the left-right placement of the Liberal party (variable <code>cps_lr_parties_1</code>) and the Conservative party (variable <code>cps19_lr_parties_2</code>) is equal to 0 in the population.</p>
<p>We can specify the test as follows:<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(<span class="at">formula =</span> <span class="fu">Pair</span>(cps19_lr_parties_1, cps19_lr_parties_2) <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">data =</span> canada,</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">alternative =</span> <span class="st">"two.sided"</span>,</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">mu =</span> <span class="dv">0</span>,</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">conf.level =</span> <span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Paired t-test

data:  Pair(cps19_lr_parties_1, cps19_lr_parties_2)
t = -95.406, df = 26718, p-value &lt; 2.2e-16
alternative hypothesis: true mean difference is not equal to 0
95 percent confidence interval:
 -2.691519 -2.583155
sample estimates:
mean difference 
      -2.637337 </code></pre>
</div>
</div>
<dl>
<dt><code>formula = Pair(cps19_lr_parties_1, cps19_lr_parties_2) ~ 1</code></dt>
<dd>
<p>We have two paired interval-ratio variables and therefore use a formula in the form <code>Pair(&lt;variable name 1&gt;, &lt;variable name 2&gt;) ~ 1</code></p>
</dd>
<dt><code>data = canada</code></dt>
<dd>
<p>We specify the data frame that we want to use.</p>
</dd>
<dt><code>alternative = "two.sided"</code></dt>
<dd>
<p>Determines whether we want to use a two sided-test, or a one-sided test. Options are “two.sided” (default), “less” (when <span class="math inline">\(H_1: \mu &lt; p\)</span>) or “greater” (when <span class="math inline">\(H_1: \mu &gt; p\)</span>).</p>
</dd>
<dt><code>mu = 0</code></dt>
<dd>
<p>The <code>mu</code> parameter should be set to the value of the mean <em>under the null hypothesis</em>. In the case of a paired sample t-test we usually hypothesize that the difference between the two means is 0 in the population, thus <code>mu = 0</code>.</p>
</dd>
<dt><code>conf.level = 0.95</code></dt>
<dd>
<p>This specifies the confidence level of the confidence interval of the difference. The default is 0.95 (a 95% confidence interval).</p>
</dd>
</dl>
</section>
<section id="reporting-a-paired-samples-t-test" class="level3" data-number="14.2.4">
<h3 data-number="14.2.4" class="anchored" data-anchor-id="reporting-a-paired-samples-t-test"><span class="header-section-number">14.2.4</span> Reporting a paired samples t-test</h3>
<p>In a paired samples t-test we compare the mean value of two interval-ratio variables. In the below example we test the null hypothesis that the mean difference of the left-right placement of the Liberal party (variable <code>cps_lr_parties_1</code>) and the Conservative party (variable <code>cps19_lr_parties_2</code>) is equal to 0 in the population.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the standard error of the mean for both variables, excluding missing observations</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="fu">MeanSE</span>(canada<span class="sc">$</span>cps19_lr_parties_1, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.01674762</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">MeanSE</span>(canada<span class="sc">$</span>cps19_lr_parties_2, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.01660731</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(<span class="at">x =</span> canada<span class="sc">$</span>cps19_lr_parties_1, </span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>           <span class="at">y =</span> canada<span class="sc">$</span>cps19_lr_parties_2,</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">data =</span> canada,</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">alternative =</span> <span class="st">"two.sided"</span>,</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>           <span class="at">mu =</span> <span class="dv">0</span>,</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>           <span class="at">paired =</span> <span class="cn">TRUE</span>,</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>           <span class="at">conf.level =</span> <span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Paired t-test

data:  canada$cps19_lr_parties_1 and canada$cps19_lr_parties_2
t = -95.406, df = 26718, p-value &lt; 2.2e-16
alternative hypothesis: true mean difference is not equal to 0
95 percent confidence interval:
 -2.691519 -2.583155
sample estimates:
mean difference 
      -2.637337 </code></pre>
</div>
</div>
<!-- *Example output SPSS (do not include the output directly in an academic paper):* -->
<!-- ![](docs/spss_paired_sample_ttest.png) -->
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Output explanation
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>In R, the output shows: +the mean difference of the observations in the sample (see ‘mean difference’). +the calculated t-value (see ‘t =’). +the degrees of freedom (see ‘df =’). +the p-value (i.e.&nbsp;the probability of finding the obtained t-value, given the null hypothesis), see p-value &lt; 2.2e-16. This is a very small number which is why R displays it like this. +the expected value under the null hypothesis (here true mean difference is not equal to 0). +the standard errors of both variables in the sample are obtained separately via <code>MeanSE()</code>.</li>
</ul>
<!-- In SPSS, the information is presented in two tables. The middle table (Paired Samples Correlations) can be ignored for now. -->
<!-- * In the table 'Paired Samples Statistics', we find -->
<!--   +the means of the variables in the sample (see cells 'Mean'). -->
<!--   +the standard errors (see cells 'Std. Error Mean'). -->
<!-- * In the SPSS table 'Paired Samples Test', we find -->
<!--   +the mean of the paired differences (see cell 'Mean'). -->
<!--   +the standard deviation of the paired differences (see cell 'Std. Deviation'). -->
<!--   +the calculated t-value (see cell 't'). -->
<!--   +the degrees of freedom (see cell 'df'). -->
<!--   +the p-value (i.e. the probability of finding the obtained t-value, given the null hypothesis. -->
</div>
</div>
<section id="reporting-1" class="level4" data-number="14.2.4.1">
<h4 data-number="14.2.4.1" class="anchored" data-anchor-id="reporting-1"><span class="header-section-number">14.2.4.1</span> Reporting</h4>
<p>The correct report includes:</p>
<ul>
<li>A conclusion about the null hypothesis;</li>
<li>the mean (in the text or as M = …) and the standard error (SE = …) of each variable.</li>
<li>The difference in the means (here -2.637337),</li>
<li>the degrees of freedom</li>
<li>p = p-value. When working with statistical software, you should report the exact p-value that is displayed.
<ul>
<li>in R, small values may be displayed using the scientific notation (e.g.&nbsp;2.2e-16 is the scientific notation of 0.00000000000000022.) This means that the value is very close to zero. R uses this notation automatically for very small numbers. In these cases, write p &lt; 0.001 in your report. <!-- + in SPSS, very small p-values may be displayed as p=0.000. However, never write p=0.000 in your report. This is simply the way SPSS displays very small p-values < 0.0005. In these cases, write p < 0.001 in your report. --></li>
</ul></li>
</ul>
<p>If you calculate the results by hand you write p &lt; “the chosen α-value”, for example, p &lt; 0.05.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Report
</div>
</div>
<div class="callout-body-container callout-body">
<p>✓ The left-right placement of the Liberal party (M = 4.25; SE = 0.017) was lower than the left-right placement of the Conservative party (M = 6.88; SE = 0.017). This difference, -2.64, was statistically significant, t(26718) = -95.406, p &lt; 0.001.</p>
</div>
</div>
</section>
</section>
<section id="independent-samples-t-test" class="level3" data-number="14.2.5">
<h3 data-number="14.2.5" class="anchored" data-anchor-id="independent-samples-t-test"><span class="header-section-number">14.2.5</span> Independent-samples t-test</h3>
<p>The independent samples t-test is used to compare whether the means of two groups are statistically significantly different. We thus have a numeric variable, for which we can calculate a mean, and a grouping variable, which is a categorical variable that determines the group membership. In our example we test whether there is a statistically significant difference in the mean placement of the Liberal party by those who are born in Canada and those who are not.</p>
<p>First we inspect the grouping variable:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(canada<span class="sc">$</span>cps19_bornin_canada)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
                          Yes                            No 
                        31556                          6046 
Don't know/ Prefer not to say 
                          220 </code></pre>
</div>
</div>
<p>It turns out this variable has three categories. We would like to ignore the Don’t know category, so we treat this as missing:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>canada <span class="ot">&lt;-</span> canada <span class="sc">|&gt;</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">cps19_bornin_canada =</span> <span class="fu">na_if</span>(cps19_bornin_canada, <span class="st">"Don't know/ Prefer not to say"</span>)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now we can run the t-test:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(<span class="at">formula =</span> cps19_lr_parties_1 <span class="sc">~</span> cps19_bornin_canada,</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">data =</span> canada,</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">alternative =</span> <span class="st">"two.sided"</span>, </span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">mu =</span> <span class="dv">0</span>,</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">conf.level =</span> .<span class="dv">95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<dl>
<dt><code>formula = cps19_lr_parties_1 ~ cps19_bornin_canada</code></dt>
<dd>
<p>We have one interval-ratio variable and one categorical variable (factor) that captures to which group an observation belongs, thus we use a formula of the form <code>&lt;interval-ratio variable&gt; ~ &lt;categorical variable&gt;</code>.</p>
</dd>
<dt><code>data = canada</code></dt>
<dd>
<p>We specify the data frame that we want to use.</p>
</dd>
<dt><code>alternative = "two.sided"</code></dt>
<dd>
<p>Determines whether we want to use a two sided-test, or a one-sided test. Options are “two.sided” (default), “less” (when <span class="math inline">\(H_1: \mu &lt; p\)</span>) or “greater” (when <span class="math inline">\(H_1: \mu &gt; p\)</span>).</p>
</dd>
<dt><code>mu = 0</code></dt>
<dd>
<p>The <code>mu</code> parameter should be set to the value of the mean <em>under the null hypothesis</em>. In the case of an independent samples t-test we usually hypothesize that the difference between the two group means is 0 in the population, thus <code>mu = 0</code>.</p>
</dd>
<dt><code>conf.level = 0.95</code></dt>
<dd>
<p>This specifies the confidence level of the confidence interval of the difference. The default is 0.95 (a 95% confidence interval).</p>
</dd>
</dl>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  cps19_lr_parties_1 by cps19_bornin_canada
t = -8.9025, df = 6809.2, p-value &lt; 2.2e-16
alternative hypothesis: true difference in means between group Yes and group No is not equal to 0
95 percent confidence interval:
 -0.4886007 -0.3122543
sample estimates:
mean in group Yes  mean in group No 
         4.196678          4.597106 </code></pre>
</div>
</div>
<p>R displays the result for the Welch Two Sample t-test, which is a version of the independent samples t-test that applies when equal variances are not assumed.</p>
</section>
<section id="reporting-an-independent-samples-t-test" class="level3" data-number="14.2.6">
<h3 data-number="14.2.6" class="anchored" data-anchor-id="reporting-an-independent-samples-t-test"><span class="header-section-number">14.2.6</span> Reporting an independent samples t-test</h3>
<p>The independent samples t-test is used to compare whether the means of two groups are statistically significantly different. We use data on the number of gym attendances last month of male and female respondents.</p>
<p><em>Example output R (do not include the output directly in an academic paper):</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the standard error of the mean per group, dropping missing values. </span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a><span class="co">#These values (mean and standard error) are needed for the report.</span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>gym <span class="sc">%&gt;%</span>                               <span class="co"># Summary by group using dplyr</span></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(gender) <span class="sc">|&gt;</span>  </span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean =</span> <span class="fu">mean</span>(gym_attendance, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>            <span class="at">se =</span> <span class="fu">MeanSE</span>(gym_attendance, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
  gender  mean     se
  &lt;chr&gt;  &lt;dbl&gt;  &lt;dbl&gt;
1 Female  3.00 0.0542
2 Male    3.97 0.0632</code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(<span class="at">formula =</span> gym_attendance <span class="sc">~</span> gender,</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">data =</span> gym,</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">alternative =</span> <span class="st">"two.sided"</span>, </span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">mu =</span> <span class="dv">0</span>,</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">conf.level =</span> .<span class="dv">95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  gym_attendance by gender
t = -11.674, df = 1944.4, p-value &lt; 2.2e-16
alternative hypothesis: true difference in means between group Female and group Male is not equal to 0
95 percent confidence interval:
 -1.1355660 -0.8089068
sample estimates:
mean in group Female   mean in group Male 
            3.001031             3.973267 </code></pre>
</div>
</div>
<!-- *Example output SPSS (do not include the output directly in an academic paper):* -->
<!-- ![](docs/spss_ind_sample_ttest.png) -->
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Output explanation
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>In R, the output shows: +the means of the variables (see ‘sample estimates’). +the calculated t-value (see ‘t =’). +the degrees of freedom (see ‘df =’). +the p-value (i.e.&nbsp;the probability of finding the obtained t-value, given the null hypothesis). +the expected value under the null hypothesis (here true mean difference is not equal to 0). +the mean of both groups is obtained separately via <code>mean()</code>.<br>
+the standard errors of both groups in the sample are obtained separately via <code>MeanSE()</code>.</li>
</ul>
<!-- In SPSS, the information is presented in two tables.  -->
<!-- * In the table 'Group Statistics', we find -->
<!--   +the means of the variables (see cells 'Mean'). -->
<!--   +the standard errors (see cells 'Std. Error Mean'). -->
<!-- * In the SPSS table 'Independent Samples Test', we find two rows. The recommendation is to ignore Levene’s test in the lower table and always look at the lowest row (‘Equal variances not assumed’) for reporting. This is Welch’s t-test. -->
<!--   +the difference between the group means (see cell 'Mean Difference'). -->
<!--   +the standard deviation of the difference between the group means (see cell 'Std. Deviation Difference'). -->
<!--   +the calculated t-value (see cell 't'). -->
<!--   +the degrees of freedom (see cell 'df'). -->
<!--   +the p-value (i.e. the probability of finding the obtained t-value, given the null hypothesis, see cell 'Sig. (2-tailed)') -->
</div>
</div>
<section id="reporting-2" class="level4" data-number="14.2.6.1">
<h4 data-number="14.2.6.1" class="anchored" data-anchor-id="reporting-2"><span class="header-section-number">14.2.6.1</span> Reporting</h4>
<p>The correct report includes:</p>
<ul>
<li>A conclusion about the null hypothesis;</li>
<li>the mean (in the text or as M = …) and the standard error (SE = …) of each variable,</li>
<li>The difference in means (here 0.972),</li>
<li>the degrees of freedom,</li>
<li>p = p-value. When working with statistical software, you should report the exact p-value that is displayed.
<ul>
<li>in R, small values may be displayed using the scientific notation (e.g.&nbsp;2.2e-16 is the scientific notation of 0.00000000000000022.) This means that the value is very close to zero. R uses this notation automatically for very small numbers. In these cases, write p &lt; 0.001 in your report. <!-- + in SPSS, very small p-values may be displayed as p=0.000. However, never write p=0.000 in your report. This is simply the way SPSS displays very small p-values < 0.0005. In these cases, write p < 0.001 in your report. --></li>
</ul></li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Report
</div>
</div>
<div class="callout-body-container callout-body">
<p>✓ The number of gym attendances of men last month (M = 3.97; SE = 0.063) was higher than the number of gym attendances of women last month (M = 3.00; SE = 0.054). This difference, 0.972, was statistically significant, t(1944.363) = 11.674, p &lt; 0.001.</p>
</div>
</div>
</section>
</section>
</section>
<section id="effect-sizes-for-t-tests" class="level2" data-number="14.3">
<h2 data-number="14.3" class="anchored" data-anchor-id="effect-sizes-for-t-tests"><span class="header-section-number">14.3</span> Effect sizes for t-tests</h2>
<p>We can calculate Cohen’s <span class="math inline">\(d\)</span> or Hedges’ <span class="math inline">\(g^*_s\)</span> as an effect size measure for a t-test. We are using function <code>cohens_d</code> and <code>hedges_g</code> from package <code>effectsize</code>.</p>
<section id="cohens-d-for-one-sample" class="level3" data-number="14.3.1">
<h3 data-number="14.3.1" class="anchored" data-anchor-id="cohens-d-for-one-sample"><span class="header-section-number">14.3.1</span> Cohen’s <span class="math inline">\(d\)</span> for one sample</h3>
<p>We are using function <code>cohens_d</code> from package <code>effectsize</code>. The parameters are pretty much the same as for the function <code>t.test</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(effectsize)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cohens_d</span>(cps19_age <span class="sc">~</span> <span class="dv">1</span>, </span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">data =</span> canada, </span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">mu =</span> <span class="fl">48.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Cohen's d |       95% CI
------------------------
0.01      | [0.00, 0.02]

- Deviation from a difference of 48.5.</code></pre>
</div>
</div>
<dl>
<dt><code>cps19_age ~ 1</code></dt>
<dd>
<p>This is the formula used for a single sample mean. In this case specify the formula in the form <code>&lt;variable name&gt; ~ 1</code>.</p>
</dd>
<dt><code>data = canada</code></dt>
<dd>
<p>We specify the data frame that we are using. Replace with your own data frame name.</p>
</dd>
<dt><code>mu = 48.5</code></dt>
<dd>
<p>We specify the value of the population mean under the null hypothesis. It is very important to specify this. If omitted, mu is set to 0 and this will often not be appropriate, especially for a one sample test.</p>
</dd>
</dl>
</section>
<section id="cohens-d-for-paired-samples" class="level3" data-number="14.3.2">
<h3 data-number="14.3.2" class="anchored" data-anchor-id="cohens-d-for-paired-samples"><span class="header-section-number">14.3.2</span> Cohen’s d for paired samples</h3>
<p>We are using function <code>cohens_d</code> from package <code>effectsize</code>. The parameters are pretty much the same as for the function <code>t.test</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(effectsize)</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cohens_d</span>(<span class="fu">Pair</span>(cps19_lr_parties_1, cps19_lr_parties_2) <span class="sc">~</span> <span class="dv">1</span>, </span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">data =</span> canada, </span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">mu =</span> <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Cohen's d |         95% CI
--------------------------
-0.58     | [-0.60, -0.57]</code></pre>
</div>
</div>
<dl>
<dt><code>Pair(cps19_lr_parties_1, cps19_lr_parties_2) ~ 1</code></dt>
<dd>
<p>We have two paired interval-ratio variables and therefore use a formula in the form <code>Pair(&lt;variable name 1&gt;, &lt;variable name 2&gt;) ~ 1</code>.</p>
</dd>
<dt><code>data = canada</code></dt>
<dd>
<p>We specify the data frame that we want to use.</p>
</dd>
<dt><code>mu = 0</code></dt>
<dd>
<p>The <code>mu</code> parameter should be set to the value of the mean <em>under the null hypothesis</em>. In the case of a paired sample t-test we usually hypothesize that the difference between the two variables is 0 in the population, thus <code>mu = 0</code>.</p>
</dd>
</dl>
</section>
<section id="hedges-g_s-for-independent-samples" class="level3" data-number="14.3.3">
<h3 data-number="14.3.3" class="anchored" data-anchor-id="hedges-g_s-for-independent-samples"><span class="header-section-number">14.3.3</span> Hedges’ <span class="math inline">\(g^*_s\)</span> for independent samples</h3>
<p>For two independent samples, we recommend calculating Hedges <span class="math inline">\(g^*_s\)</span> as effect size measure (<a href="https://doi.org/10.31234/osf.io/tu6mp">Delacre et al.&nbsp;2021</a>). Its interpretation is similar to Cohen’s <span class="math inline">\(d\)</span>, but bias-corrected and adapted to a situation when equal variances cannot be assumed. The values are very similar to Cohen’s <span class="math inline">\(d\)</span> for larger samples.</p>
<p>Note that for our example we use the modified version of variable <code>cps19_bornin_canada</code> (see <a href="#independent-samples-t-test">Independent-samples t-test</a>):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(effectsize)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hedges_g</span>(cps19_lr_parties_1 <span class="sc">~</span> cps19_bornin_canada, </span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">data =</span> canada, </span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">mu =</span> <span class="dv">0</span>,</span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">pooled_sd =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Hedges' g |         95% CI
--------------------------
-0.14     | [-0.17, -0.11]

- Estimated using un-pooled SD.</code></pre>
</div>
</div>
<dl>
<dt><code>cps19_lr_parties_1 ~ cps19_bornin_canada</code></dt>
<dd>
<p>We have one interval-ratio variable and one categorical variable (factor) that captures to which group an observation belongs, thus we use a formula of the form <code>&lt;interval-ratio variable&gt; ~ &lt;categorical variable&gt;</code>.</p>
</dd>
<dt><code>data = canada</code></dt>
<dd>
<p>We specify the data frame that we want to use.</p>
</dd>
<dt><code>mu = 0</code></dt>
<dd>
<p>The <code>mu</code> parameter should be set to the value of the mean <em>under the null hypothesis</em>. In the case of an independent samples t-test we usually hypothesize that the difference between the two group means is 0 in the population, thus <code>mu = 0</code>.</p>
</dd>
<dt><code>pooled_sd = FALSE</code></dt>
<dd>
<p>This specifies that we do not use the pooled standard deviation, which is recommended when using Welch’ t-test (not assuming variances are equal), which <code>t.test</code> does by default for the independent samples t-test.</p>
</dd>
</dl>
</section>
<section id="reporting-measures-of-association-for-t-tests" class="level3" data-number="14.3.4">
<h3 data-number="14.3.4" class="anchored" data-anchor-id="reporting-measures-of-association-for-t-tests"><span class="header-section-number">14.3.4</span> Reporting measures of association for t-tests</h3>
<section id="cohens-d" class="level4" data-number="14.3.4.1">
<h4 data-number="14.3.4.1" class="anchored" data-anchor-id="cohens-d"><span class="header-section-number">14.3.4.1</span> Cohen’s d</h4>
<p>Cohen’s d, or standardized mean difference, is one of the most common ways to measure effect size for t-tests. There are different ways to calculate it, depending on the type of t-test but the reporting is the same. Here, I show Cohen’s d based on the one-sample t-test above.</p>
<p><em>Example output R (do not include the output directly in an academic paper):</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">MeanSE</span>(fruit<span class="sc">$</span>fruitconsumption, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.714986</code></pre>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(<span class="at">x =</span> fruit<span class="sc">$</span>fruitconsumption,</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>           <span class="at">alternative =</span> <span class="st">"two.sided"</span>,</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">mu =</span> <span class="dv">100</span>,</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">conf.level =</span> <span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  fruit$fruitconsumption
t = -5.831, df = 33, p-value = 1.587e-06
alternative hypothesis: true mean is not equal to 100
95 percent confidence interval:
 86.51084 93.48916
sample estimates:
mean of x 
       90 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(effectsize)</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cohens_d</span>(fruitconsumption <span class="sc">~</span> <span class="dv">1</span>, </span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">data =</span> fruit, </span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">mu =</span> <span class="dv">100</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Cohen's d |         95% CI
--------------------------
-1.00     | [-1.41, -0.58]

- Deviation from a difference of 100.</code></pre>
</div>
</div>
<!-- *Example output SPSS (do not include the output directly in an academic paper):* -->
<!-- ![](docs/spss_effect_ttest.png) -->
<!-- ::: callout-note -->
<!-- #### Output explanation -->
<!-- In SPSS, the value for Cohen's d is shown in the cell 'Point Estimate'. -->
<!-- ::: -->
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Interpretation
</div>
</div>
<div class="callout-body-container callout-body">
<p>The Cohen’s d value range is from -∞ to +∞ and values can therefore be negative. If d is negative, it simply means that the group mean of the sample (or in the case of the paired/independent sample t-test the first group) is lower than the group of mean of population (or in the case of the paired/independent sample t-test the second group).</p>
<p>A Cohen’s d of 1 means that the difference between the sample mean and hypothesized population mean is 1 standard deviation. A Cohen’s d of 0.5 means that the difference between the sample mean and hypothesized mean is 0.5 standard deviations (half a standard deviation).</p>
<p>The following rule of thumbs are often applied for interpreting Cohen’s d:</p>
<ul>
<li><p>A value of at least <strong>0.2</strong> represents a <strong>small</strong> effect size.</p></li>
<li><p>A value of at least <strong>0.5</strong> represents a <strong>medium</strong> effect size.</p></li>
<li><p>A value of at least <strong>0.8</strong> represents a <strong>large</strong> effect size.</p></li>
</ul>
<p>As always with rules of thumbs, be careful and consider the type of data that you are working with.</p>
</div>
</div>
</section>
<section id="reporting-3" class="level4" data-number="14.3.4.2">
<h4 data-number="14.3.4.2" class="anchored" data-anchor-id="reporting-3"><span class="header-section-number">14.3.4.2</span> Reporting</h4>
<p>If you have calculated Cohen’s d for a t-test, you can add it to the report:</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Report
</div>
</div>
<div class="callout-body-container callout-body">
<p>✓ The mean fruit consumption of students was 90 (SE = 1.71). This is not significantly different from the mean fruit consumption of the whole population (t(33) = -1.167, p = 0.252). This represents a large difference, d = -1.00.</p>
</div>
</div>
</section>
<section id="hedges-g_s-for-independent-samples-1" class="level4" data-number="14.3.4.3">
<h4 data-number="14.3.4.3" class="anchored" data-anchor-id="hedges-g_s-for-independent-samples-1"><span class="header-section-number">14.3.4.3</span> Hedges’ <span class="math inline">\(g^*_s\)</span> for independent samples</h4>
<p>Cohen’s d and Hedges <span class="math inline">\(g^*_s\)</span> are largely comparable, but Hedges modification is considered more robust for small samples.</p>
<p><em>Example output R (do not include the output directly in an academic paper):</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">MeanSE</span>(fruit<span class="sc">$</span>fruitconsumption, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.714986</code></pre>
</div>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(<span class="at">x =</span> fruit<span class="sc">$</span>fruitconsumption,</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>           <span class="at">alternative =</span> <span class="st">"two.sided"</span>,</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">mu =</span> <span class="dv">100</span>,</span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">conf.level =</span> <span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  fruit$fruitconsumption
t = -5.831, df = 33, p-value = 1.587e-06
alternative hypothesis: true mean is not equal to 100
95 percent confidence interval:
 86.51084 93.48916
sample estimates:
mean of x 
       90 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(effectsize)</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hedges_g</span>(fruitconsumption <span class="sc">~</span> <span class="dv">1</span>, </span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">data =</span> fruit, </span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">mu =</span> <span class="dv">100</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Hedges' g |         95% CI
--------------------------
-0.98     | [-1.38, -0.57]

- Deviation from a difference of 100.</code></pre>
</div>
</div>
<!-- *Example output SPSS (do not include the output directly in an academic paper):* -->
<!-- ![](docs/spss_effect_ttest.png) -->
<!-- ::: callout-note -->
<!-- #### Output explanation -->
<!-- In SPSS, the value for Hedges' $g_s^*$ is shown in the cell 'Point Estimate'. -->
<!-- ::: -->
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Interpretation
</div>
</div>
<div class="callout-body-container callout-body">
<p>The interpretation of Hedges’ <span class="math inline">\(g_s^*\)</span> is similar to Cohen’s D. A Hedges’ <span class="math inline">\(g_s^*\)</span> of 1 means that the difference between the two sample means is 1 standard deviation. A Hedges’ <span class="math inline">\(g_s^*\)</span> of 0.5 means that the difference between the two sample means is 0.5 standard deviations (half a standard deviation).</p>
<p>The following rule of thumbs are often applied for interpreting Cohen’s d and Hedges’ <span class="math inline">\(g_s^*\)</span>:</p>
<ul>
<li><p>A value of at least <strong>0.2</strong> represents a <strong>small</strong> effect size.</p></li>
<li><p>A value of at least <strong>0.5</strong> represents a <strong>medium</strong> effect size.</p></li>
<li><p>A value of at least <strong>0.8</strong> represents a <strong>large</strong> effect size.</p></li>
</ul>
<p>As always with rules of thumbs, be careful and consider the type of data that you are working with.</p>
</div>
</div>
</section>
<section id="reporting-4" class="level4" data-number="14.3.4.4">
<h4 data-number="14.3.4.4" class="anchored" data-anchor-id="reporting-4"><span class="header-section-number">14.3.4.4</span> Reporting</h4>
<p>The Hedges’ <span class="math inline">\(g_s^*\)</span> effect size is often included after the independent samples t-test, for example:</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Report
</div>
</div>
<div class="callout-body-container callout-body">
<p>✓ The mean fruit consumption of students was 90 (SE = 1.71). This is not significantly different from the mean fruit consumption of the whole population (t(33) = -1.167, p = 0.252). This represents a large difference, <span class="math inline">\(g_s^*\)</span> = -0.98.</p>
</div>
</div>


</section>
</section>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>In this overview we use the co-called ‘formula interface’ to t.test. You can also use the so-called traditional interface. For the one-sample t-test example, the equivalent code is:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(<span class="at">x =</span> canada<span class="sc">$</span>cps19_age,</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">alternative =</span> <span class="st">"two.sided"</span>,</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">mu =</span> <span class="fl">48.5</span>,</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">conf.level =</span> <span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  canada$cps19_age
t = 2.2395, df = 37821, p-value = 0.02513
alternative hypothesis: true mean is not equal to 48.5
95 percent confidence interval:
 48.52387 48.85871
sample estimates:
mean of x 
 48.69129 </code></pre>
</div>
</div>
<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></li>
<li id="fn2"><p>In this overview we use the co-called ‘formula interface’ to t.test. You can also use the so-called traditional interface. For the paired samples t-test example, the equivalent code is:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(<span class="at">x =</span> canada<span class="sc">$</span>cps19_lr_parties_1, </span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> canada<span class="sc">$</span>cps19_lr_parties_2,</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">data =</span> canada,</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">alternative =</span> <span class="st">"two.sided"</span>,</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">mu =</span> <span class="dv">0</span>,</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">paired =</span> <span class="cn">TRUE</span>,</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">conf.level =</span> <span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Paired t-test

data:  canada$cps19_lr_parties_1 and canada$cps19_lr_parties_2
t = -95.406, df = 26718, p-value &lt; 2.2e-16
alternative hypothesis: true mean difference is not equal to 0
95 percent confidence interval:
 -2.691519 -2.583155
sample estimates:
mean difference 
      -2.637337 </code></pre>
</div>
</div>
<p>In this case, do not forget to include <code>paired = TRUE</code>.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./analysis_07_chi_squared.html" class="pagination-link" aria-label="Chi-squared and measures of association">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Chi-squared and measures of association</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./analysis_09_power_analysis.html" class="pagination-link" aria-label="Power analysis">
        <span class="nav-page-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Power analysis</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>